### ISSUE TITLE
How to detect language for a String?

### ISSUE THREAD

**Issue by Ridermansb** [blakeembrey/node-language-detect#3]
I have a raw content of text and a file name but I dont have a file in disk.

How to detect without save a file in disk, just pass filename and raw content of text?

**Comment by blakeembrey** [comment]
There are the methods: `filename`, `shebang` and `classify` which are working together on the stream contents. I can add a synchronous method using contents now for you though.

**Comment by blakeembrey** [comment]
The new methods and README are now available and published with `v1.1.0`.

**Comment by Ridermansb** [comment]
This is awesome @blakeembrey thanks.

There is a file on disk, so the filename will only serve to try to detect the language using naming conventions (name and extension).
So theoretically we do not need to pass `__dirname / + filename`

**Comment by blakeembrey** [comment]
Yes, I know. Just pass it whatever you need, but for the most part I would be using a user file. The code itself already uses only the basename.
